### ISSUE TITLE
Include arc functions helpers

### ISSUE THREAD

**Issue by kristoferjoseph** [enhance-dev/enhance#3]
`arc.events.publish`
Events subscribe pub/sub
Similar to begin/data

**Comment by tbeseda** [comment]
_If Enhance gets "jobs" (which map to Architect primitives)..._

Those could include `scheduled`, `events`, and `tables-streams`. (I don't think we want `queues`.)

For those 3, I think the only `@architect/functions` helper needed by Enhance consumers would be the one you listed: `arc.events.publish`.  
The `scheduled` handler is invoked as is on a schedule and the `tables-streams` does the same when a doc changes in Dynamo.

The only other part of `@architect/functions` I might like is `#tables()` but that has a whole collision with "Begin Data" which is probably another conversation.
