### ISSUE TITLE
.mjs files

### ISSUE THREAD

**Issue by jessehattabaugh** [enhance-dev/enhance#4]
Enhance can't find any of my elements unless I use .mjs and this makes me sad; JavaScript belongs in .js files like our lord and savior Brendan Eich intended!!!

Architect allows for this: https://arc.codes/docs/en/guides/developer-experience/using-esm#es-modules-with-package.json

**Comment by kristoferjoseph** [comment]
I hear you!
I hate it more than you can imagine, but this was the least horrible solution based on npm and node resolution issues in mixed projects.

using `.mjs` files will **always** work, where as there are too many caveats to cover and explain until `.cjs` goes the way of the dodo.

Sorry, it sucks.
